### ISSUE TITLE
Location selection

### ISSUE THREAD

**Issue by haganka** [haganka/Dining-in-the-Rough#2]
# Definition of Done

Add two event listeners: 
1. "Use my current location" 
2. "Search" 

Has function for "use my current location" with API call for latitude/longitude
Stores latitude and longitude as variables

Has function for "search" 
If user enters zip code, stores var zip code

**Comment by mcginnis92** [comment]
Also need to take into account taking a zip code into a latitude/longitude so that it can be recognized by the API
