### ISSUE TITLE
UI Issue: Mobile Responsiveness

### ISSUE THREAD

**Issue by mcginnis92** [haganka/Dining-in-the-Rough#47]
DOD:

Site is mobile responsive and all images and divs conform to the screen size accordingly.

**Comment by cybernetck** [comment]
making images in results responsive - adding img-responsive to statement on line 117 in main.js

 ` 
var imageAppend = '<div class="col-md-4"><img class="imageThumbs img-responsive" + src=' + image + '></div>' `
